(package "eglot-languagetool"
         "0.1.0"
         "Eglot Clients for LanguageTool")

(website-url "https://github.com/emacs-languagetool/eglot-languagetool")
(keywords "convenience" "eglot" "languagetool" "checker")

(package-file "eglot-languagetool.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "24.3")
(depends-on "eglot")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
